package es.iesjandula.administracion.gestion_ausencias.jframes;

import java.awt.Toolkit;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

import es.iesjandula.administracion.exceptions.IESJandulaException;
import es.iesjandula.administracion.gestion_ausencias.models.ApplicationGestion;

/**
 * @author David Martinez
 *
 */
public class ConfigurationWindowGestion extends javax.swing.JFrame
{
	/** Attribute logger */
	private static final Logger logger = LogManager.getLogger();

	/** Attribute starterWindow */
	private StarterWindow starterWindow;

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonAceptar;
	private javax.swing.JButton jButtonPreCargar;
	private javax.swing.JButton jButtonSalir;
	private javax.swing.JEditorPane jEditorPaneNewUrl;
	private javax.swing.JLabel jLabelActualEmail;
	private javax.swing.JLabel jLabelBackground;
	private javax.swing.JLabel jLabelConexionMongoText;
	private javax.swing.JLabel jLabelEditarEmail;
	private javax.swing.JLabel jLabelEditarUrl;
	private javax.swing.JLabel jLabelHints;
	private javax.swing.JLabel jLabelJandulaLogo;
	private javax.swing.JScrollPane jScrollPane;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextPane jTextPaneActualUrl;
	private javax.swing.JTextPane jTextPaneEmail;
	// End of variables declaration//GEN-END:variables

	/**
	 * Creates new form Configuration
	 */
	public ConfigurationWindowGestion(StarterWindow starterWindow)
	{
		this.initComponents();
		this.jLabelBackground.setIcon(new ImageIcon("./images/background2.jpg"));
		this.setIconImage(Toolkit.getDefaultToolkit().getImage("./images/jandula.png"));
		this.jLabelJandulaLogo.setIcon(new ImageIcon("./images/jandula.png"));
		this.setTitle("CONFIGURATION");
		this.starterWindow = starterWindow;
		this.setResizable(false);
		this.setLocationRelativeTo(null);
		try
		{
			this.jTextPaneActualUrl.setText(new ApplicationGestion().getSheetUrl().trim());
			this.jLabelActualEmail.setText(new ApplicationGestion().getEmail().trim());
		}
		catch (IESJandulaException exception)
		{
			String error = "IO Exception getSheetUrl ";
			ConfigurationWindowGestion.logger.error(error, exception);
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		this.jButtonSalir = new javax.swing.JButton();
		this.jScrollPane1 = new javax.swing.JScrollPane();
		this.jTextPaneActualUrl = new javax.swing.JTextPane();
		this.jLabelConexionMongoText = new javax.swing.JLabel();
		this.jLabelEditarUrl = new javax.swing.JLabel();
		this.jScrollPane = new javax.swing.JScrollPane();
		this.jEditorPaneNewUrl = new javax.swing.JEditorPane();
		this.jButtonPreCargar = new javax.swing.JButton();
		this.jButtonAceptar = new javax.swing.JButton();
		this.jScrollPane2 = new javax.swing.JScrollPane();
		this.jTextPaneEmail = new javax.swing.JTextPane();
		this.jLabelHints = new javax.swing.JLabel();
		this.jLabelActualEmail = new javax.swing.JLabel();
		this.jLabelJandulaLogo = new javax.swing.JLabel();
		this.jLabelEditarEmail = new javax.swing.JLabel();
		this.jLabelBackground = new javax.swing.JLabel();

		this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		this.getContentPane().setLayout(new AbsoluteLayout());

		this.jButtonSalir.setBackground(new java.awt.Color(203, 203, 203));
		this.jButtonSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		this.jButtonSalir.setText("VOLVER");
		this.jButtonSalir.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				ConfigurationWindowGestion.this.jButtonSalirActionPerformed(evt);
			}
		});
		this.getContentPane().add(this.jButtonSalir, new AbsoluteConstraints(720, 310, 111, 38));

		this.jScrollPane1.setViewportView(this.jTextPaneActualUrl);

		this.getContentPane().add(this.jScrollPane1, new AbsoluteConstraints(10, 50, 830, 40));

		this.jLabelConexionMongoText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		this.jLabelConexionMongoText.setText("GOOGLE SHEET ACTUAL URL");
		this.getContentPane().add(this.jLabelConexionMongoText,
				new AbsoluteConstraints(10, 20, 400, -1));

		this.jLabelEditarUrl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		this.jLabelEditarUrl.setText("EDITAR URL:");
		this.getContentPane().add(this.jLabelEditarUrl, new AbsoluteConstraints(10, 130, 410, -1));

		this.jScrollPane.setViewportView(this.jEditorPaneNewUrl);

		this.getContentPane().add(this.jScrollPane, new AbsoluteConstraints(10, 160, 830, 50));

		this.jButtonPreCargar.setBackground(new java.awt.Color(203, 203, 203));
		this.jButtonPreCargar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		this.jButtonPreCargar.setText("PRE-CARGAR");
		this.jButtonPreCargar.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				ConfigurationWindowGestion.this.jButtonPreCargarActionPerformed(evt);
			}
		});
		this.getContentPane().add(this.jButtonPreCargar, new AbsoluteConstraints(530, 310, -1, 40));

		this.jButtonAceptar.setBackground(new java.awt.Color(203, 203, 203));
		this.jButtonAceptar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		this.jButtonAceptar.setText("GUARDAR");
		this.jButtonAceptar.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				ConfigurationWindowGestion.this.jButtonAceptarActionPerformed(evt);
			}
		});
		this.getContentPane().add(this.jButtonAceptar, new AbsoluteConstraints(340, 310, 111, 38));

		this.jScrollPane2.setViewportView(this.jTextPaneEmail);

		this.getContentPane().add(this.jScrollPane2, new AbsoluteConstraints(10, 250, 440, 30));

		this.jLabelHints.setBackground(new java.awt.Color(255, 253, 238));
		this.jLabelHints.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		this.jLabelHints.setForeground(new java.awt.Color(2, 78, 0));
		this.jLabelHints.setText(
				"PISTA: ¡Utiliza el cuadro de texto de mas abajo para pre-visualizar un nuevo estado y presiona guardar si lo deseas!");
		this.jLabelHints.setOpaque(true);
		this.getContentPane().add(this.jLabelHints, new AbsoluteConstraints(10, 100, -1, -1));

		this.jLabelActualEmail.setBackground(new java.awt.Color(255, 252, 231));
		this.jLabelActualEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jLabelActualEmail.setForeground(new java.awt.Color(0, 79, 0));
		this.jLabelActualEmail.setOpaque(true);
		this.getContentPane().add(this.jLabelActualEmail, new AbsoluteConstraints(200, 220, 640, 20));

		this.jLabelJandulaLogo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		this.getContentPane().add(this.jLabelJandulaLogo, new AbsoluteConstraints(20, 280, 390, 90));

		this.jLabelEditarEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		this.jLabelEditarEmail.setText("EDITAR EMAIL DE INICIO: ->");
		this.getContentPane().add(this.jLabelEditarEmail, new AbsoluteConstraints(10, 220, -1, -1));
		this.getContentPane().add(this.jLabelBackground, new AbsoluteConstraints(0, 0, 850, 390));

		this.pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * Method jButtonSalirActionPerformed
	 *
	 * @param evt
	 */
	private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jButtonSalirActionPerformed
		this.starterWindow.setVisible(true);
		this.starterWindow.setLocationRelativeTo(null);
		this.dispose();
	}// GEN-LAST:event_jButtonSalirActionPerformed

	/**
	 * Method jButtonAceptarActionPerformed
	 *
	 * @param evt
	 */
	private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jButtonAceptarActionPerformed
		ApplicationGestion application = new ApplicationGestion();
		try
		{
			application.storeNewConfiguration(
					this.jEditorPaneNewUrl.getText().trim() + "\n" + this.jTextPaneEmail.getText());
			JOptionPane.showMessageDialog(null, "CONFIGURACION GUARDADA CON EXITO");
			this.starterWindow.setVisible(true);
			this.starterWindow.setLocationRelativeTo(null);
			this.dispose();
		}
		catch (IESJandulaException exception)
		{
			JOptionPane.showMessageDialog(null, "ERROR AL GUARDAR CONFIGURACION");
			String error = "FileNotFoundException storeNewConfiguration ";
			ConfigurationWindowGestion.logger.error(error, exception);
		}
	}// GEN-LAST:event_jButtonAceptarActionPerformed

	/**
	 * Method jButtonPreCargarActionPerformed
	 *
	 * @param evt
	 */
	private void jButtonPreCargarActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jButtonPreCargarActionPerformed
		this.jTextPaneActualUrl.setText(this.jEditorPaneNewUrl.getText().trim());
		this.jLabelActualEmail.setText(this.jTextPaneEmail.getText().trim());
	}// GEN-LAST:event_jButtonPreCargarActionPerformed
}
