
package es.iesjandula.administracion.gestion_ausencias.jframes;

import java.awt.Toolkit;

import javax.swing.ImageIcon;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import es.iesjandula.administracion.exceptions.IESJandulaException;
import es.iesjandula.administracion.gestion_ausencias.models.ApplicationGestion;
import es.iesjandula.administracion.windows.AdministracionMenu;

/**
 * @author David Martinez
 *
 */
public class StarterWindow extends javax.swing.JFrame
{
	/** Attribute logger */
	private static final Logger logger = LogManager.getLogger();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackButton;
    private javax.swing.JButton jButtonSetting;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelJandulaLogo;
    // End of variables declaration//GEN-END:variables

	/**
	 * Creates new form StarterWindow
	 */
	public StarterWindow()
	{
		this.initComponents();
		this.setLocationRelativeTo(null);
		this.setResizable(false);

		this.setIconImage(Toolkit.getDefaultToolkit().getImage("./images/jandula.png"));
		this.setTitle("START APP");
		this.jButtonSetting.setIcon(new ImageIcon("./images/setting.png"));
		this.jLabelBackground.setIcon(new ImageIcon("./images/background2.jpg"));
		this.jLabelJandulaLogo.setIcon(new ImageIcon("./images/jandula.png"));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonStart = new javax.swing.JButton();
        jButtonSetting = new javax.swing.JButton();
        jButtonBackButton = new javax.swing.JButton();
        jLabelJandulaLogo = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonStart.setBackground(new java.awt.Color(203, 203, 203));
        jButtonStart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonStart.setText("START APPLICATION");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 59));

        jButtonSetting.setBackground(new java.awt.Color(254, 255, 221));
        jButtonSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSettingActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 70, 59));

        jButtonBackButton.setBackground(new java.awt.Color(203, 203, 203));
        jButtonBackButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBackButton.setText("VOLVER");
        jButtonBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jLabelJandulaLogo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelJandulaLogo.setText("I.E.S JANDULA GUARDIAS");
        getContentPane().add(jLabelJandulaLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 390, 90));
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackButtonActionPerformed
        AdministracionMenu administracionMenu = new AdministracionMenu();
        administracionMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackButtonActionPerformed

	/**
	 * Method jButtonStartActionPerformed
	 *
	 * @param evt
	 */
	private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jButtonStartActionPerformed
		this.setVisible(false);
		ApplicationGestion application = new ApplicationGestion();
		try
		{
			application.run(new ApplicationGestion().getSheetUrl(), new ApplicationGestion().getEmail());
		}
		catch (IESJandulaException exception)
		{
			String error = "IO Exception getSheetUrl ";
			StarterWindow.logger.error(error, exception);
		}

	}// GEN-LAST:event_jButtonStartActionPerformed

	/**
	 * Method jButtonSettingActionPerformed
	 *
	 * @param evt
	 */
	private void jButtonSettingActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jButtonSettingActionPerformed
		ConfigurationWindowGestion configurationWindow = new ConfigurationWindowGestion(this);
		configurationWindow.setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_jButtonSettingActionPerformed

}
