/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.iesjandula.administracion.windows;

import es.iesjandula.administracion.gestion_ausencias.LaunchGestionAusencias;
import es.iesjandula.administracion.huelga_alumnos.LaunchHuelgas;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author USUARIO
 */
public class AdministracionMenu extends javax.swing.JFrame
{
	/** Attribute logger */
	private static final Logger logger = LogManager.getLogger();

	/**
	 * Creates new form AdministracionMenu
	 */
	public AdministracionMenu()
	{
		initComponents();
                this.setIconImage(Toolkit.getDefaultToolkit().getImage("./images/jandula.png"));
		this.setTitle("Programa de administración del Instituto de Jandula");
                this.jLabelBackground.setIcon(new ImageIcon("./images/background2.jpg"));
                this.jLabelJandulaLogo.setIcon(new ImageIcon("./images/jandula.png"));
                this.setResizable(false);
                this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGestionAusencias = new javax.swing.JButton();
        jButtonGestionHuelgasAlumnos = new javax.swing.JButton();
        jLabelJandulaLogo = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonGestionAusencias.setBackground(new java.awt.Color(203, 203, 203));
        jButtonGestionAusencias.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButtonGestionAusencias.setText("GESTION AUSENCIAS");
        jButtonGestionAusencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionAusenciasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGestionAusencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 290, 70));

        jButtonGestionHuelgasAlumnos.setBackground(new java.awt.Color(203, 203, 203));
        jButtonGestionHuelgasAlumnos.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButtonGestionHuelgasAlumnos.setText("GESTION HUELGAS ALUMNOS");
        jButtonGestionHuelgasAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionHuelgasAlumnosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGestionHuelgasAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 290, 70));

        jLabelJandulaLogo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelJandulaLogo.setText("PROGRAMA DE ADMINISTRACION DEL INSTITUTO I.E.S  JANDULA");
        getContentPane().add(jLabelJandulaLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 640, 90));
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGestionAusenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionAusenciasActionPerformed
        LaunchGestionAusencias launchGestionAusencias = new LaunchGestionAusencias();
        launchGestionAusencias.run();
        this.dispose();
    }//GEN-LAST:event_jButtonGestionAusenciasActionPerformed

    private void jButtonGestionHuelgasAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionHuelgasAlumnosActionPerformed
        LaunchHuelgas launchHuelgas = new LaunchHuelgas();
        launchHuelgas.run();
        this.dispose();
    }//GEN-LAST:event_jButtonGestionHuelgasAlumnosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGestionAusencias;
    private javax.swing.JButton jButtonGestionHuelgasAlumnos;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelJandulaLogo;
    // End of variables declaration//GEN-END:variables
}
