/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.iesjandula.administracion.huelga_alumnos;

import java.awt.Toolkit;
import java.util.List;

import javax.swing.ImageIcon;

import es.iesjandula.administracion.huelga_alumnos.utils.Alumn;
import es.iesjandula.administracion.windows.AdministracionMenu;

/**
 * @author David Martinez
 *
 */
public class MenuHuelga extends javax.swing.JFrame
{

	/** Attribute alumnList */
	private List<Alumn> alumnList;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackButton;
    private javax.swing.JButton jButtonConfigurationSetting;
    private javax.swing.JButton jButtonConsulta;
    private javax.swing.JButton jButtonCursoA;
    private javax.swing.JButton jButtonHuelga;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelJandulaLogo;
    // End of variables declaration//GEN-END:variables

	/**
	 * Constructor for create new MenuHuelga
	 *
	 * @param alumnList
	 */
	public MenuHuelga(List<Alumn> alumnList)
	{
		this.initComponents();
		this.setResizable(false);
		this.jButtonConfigurationSetting.setIcon(new ImageIcon("./images/setting.png"));
		this.alumnList = alumnList;
		this.jLabelJandulaLogo.setIcon(new ImageIcon("./images/jandula.png"));
		this.setIconImage(Toolkit.getDefaultToolkit().getImage("./images/jandula.png"));
		this.jLabelBackground.setIcon(new ImageIcon("./images/background2.jpg"));
		this.setTitle("MENU HUELGA");
		this.setLocationRelativeTo(null);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConsulta = new javax.swing.JButton();
        jButtonBackButton = new javax.swing.JButton();
        jButtonCursoA = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonHuelga = new javax.swing.JButton();
        jButtonConfigurationSetting = new javax.swing.JButton();
        jLabelJandulaLogo = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonConsulta.setBackground(new java.awt.Color(203, 203, 203));
        jButtonConsulta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonConsulta.setText("CONSULTA");
        jButtonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 170, 53));

        jButtonBackButton.setBackground(new java.awt.Color(203, 203, 203));
        jButtonBackButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBackButton.setText("VOLVER");
        jButtonBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, -1, -1));

        jButtonCursoA.setBackground(new java.awt.Color(203, 203, 203));
        jButtonCursoA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCursoA.setText("CURSO HUELGA");
        jButtonCursoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCursoAActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCursoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 170, 53));

        jButtonSalir.setBackground(new java.awt.Color(203, 203, 203));
        jButtonSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 170, 53));

        jButtonHuelga.setBackground(new java.awt.Color(203, 203, 203));
        jButtonHuelga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonHuelga.setText("HUELGA");
        jButtonHuelga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHuelgaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHuelga, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 170, 53));

        jButtonConfigurationSetting.setBackground(new java.awt.Color(255, 246, 217));
        jButtonConfigurationSetting.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonConfigurationSetting.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConfigurationSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConfigurationSettingMouseClicked(evt);
            }
        });
        jButtonConfigurationSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfigurationSettingActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfigurationSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 70, 50));

        jLabelJandulaLogo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelJandulaLogo.setText("I.E.S JANDULA - HUELGAS");
        getContentPane().add(jLabelJandulaLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 390, 90));
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackButtonActionPerformed
        AdministracionMenu administracionMenu = new AdministracionMenu();
        administracionMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackButtonActionPerformed

	/**
	 * Method jButtonConfigurationSettingActionPerformed
	 *
	 * @param evt
	 */
	private void jButtonConfigurationSettingActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jButtonConfigurationSettingActionPerformed
		ConfigurationWindow configurationWindow = new ConfigurationWindow(this);
		configurationWindow.setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_jButtonConfigurationSettingActionPerformed

	/**
	 * Method jButtonConfigurationSettingMouseClicked
	 *
	 * @param evt
	 */
	private void jButtonConfigurationSettingMouseClicked(java.awt.event.MouseEvent evt)
	{// GEN-FIRST:event_jButtonConfigurationSettingMouseClicked

	}// GEN-LAST:event_jButtonConfigurationSettingMouseClicked

	/**
	 * Method jButtonHuelgaActionPerformed
	 *
	 * @param evt
	 */
	private void jButtonHuelgaActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jButtonHuelgaActionPerformed
		Huelga huelga = new Huelga(this.alumnList);
		huelga.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_jButtonHuelgaActionPerformed

	/**
	 * Method jButtonConsultaActionPerformed
	 *
	 * @param evt
	 */
	private void jButtonConsultaActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jButtonConsultaActionPerformed
		ConsultaHuelga consultaHuelga = new ConsultaHuelga(this.alumnList);
		consultaHuelga.setVisible(true);
		this.dispose();

	}// GEN-LAST:event_jButtonConsultaActionPerformed

	/**
	 * Method jButtonSalirActionPerformed
	 *
	 * @param evt
	 */
	private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jButtonSalirActionPerformed
		System.exit(0);
	}// GEN-LAST:event_jButtonSalirActionPerformed

	/**
	 * Method jButtonCursoAActionPerformed
	 *
	 * @param evt
	 */
	private void jButtonCursoAActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jButtonCursoAActionPerformed
		ConsultaHuelgaCurso consultaHuelgaCurso = new ConsultaHuelgaCurso(this.alumnList);
		consultaHuelgaCurso.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_jButtonCursoAActionPerformed

}
